export {
	requestPersistentStorage,
	type SaveFailure,
	type SaveResult,
	safeGetItem,
	safeRemoveItem,
	safeSetItem,
} from "./local";
export {
	childrenOf,
	copyTitle,
	countDocsUnder,
	createDoc,
	createFolder,
	daysLeft,
	displayTitle,
	duplicateDoc,
	makeId,
	moveDoc,
	moveFolder,
	purge,
	purgeExpired,
	renameFolder,
	repairPaths,
	restore,
	SHEET_LIMIT,
	TRASH_DAYS,
	trashDoc,
	trashFolder,
	updateDoc,
	usedSheets,
} from "./operations";
export {
	ancestorIds,
	canMoveFolder,
	fullPath,
	isUnder,
	parentId,
	pathNames,
	ROOT,
	reparent,
} from "./path";
export {
	type DocContent,
	hasDoc,
	INDEX_KEY,
	mutateIndex,
	readDoc,
	readIndex,
	readLastOpened,
	removeDoc,
	subscribeToIndex,
	tidy,
	writeDoc,
	writeIndex,
	writeLastOpened,
} from "./store";
export {
	type DocEntry,
	emptyIndex,
	type FolderEntry,
	type Path,
	type StoreIndex,
	type TrashEntry,
} from "./types";
export { useStoreIndex } from "./useStoreIndex";
