/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ApiArchiveRouteImport } from './routes/api.archive'
import { Route as AppFFolderIdRouteImport } from './routes/_app.f.$folderId'
import { Route as AppWDocIdRouteImport } from './routes/_app.w.$docId'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiArchiveDocDocIdRouteImport } from './routes/api.archive.doc.$docId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArchiveRoute = ApiArchiveRouteImport.update({
  id: '/api/archive',
  path: '/api/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFFolderIdRoute = AppFFolderIdRouteImport.update({
  id: '/f/$folderId',
  path: '/f/$folderId',
  getParentRoute: () => AppRoute,
} as any)
const AppWDocIdRoute = AppWDocIdRouteImport.update({
  id: '/w/$docId',
  path: '/w/$docId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArchiveDocDocIdRoute = ApiArchiveDocDocIdRouteImport.update({
  id: '/doc/$docId',
  path: '/doc/$docId',
  getParentRoute: () => ApiArchiveRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/archive': typeof ApiArchiveRouteWithChildren
  '/f/$folderId': typeof AppFFolderIdRoute
  '/w/$docId': typeof AppWDocIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/archive/doc/$docId': typeof ApiArchiveDocDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/archive': typeof ApiArchiveRouteWithChildren
  '/f/$folderId': typeof AppFFolderIdRoute
  '/w/$docId': typeof AppWDocIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/archive/doc/$docId': typeof ApiArchiveDocDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/api/archive': typeof ApiArchiveRouteWithChildren
  '/_app/f/$folderId': typeof AppFFolderIdRoute
  '/_app/w/$docId': typeof AppWDocIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/archive/doc/$docId': typeof ApiArchiveDocDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/archive'
    | '/f/$folderId'
    | '/w/$docId'
    | '/api/auth/$'
    | '/api/archive/doc/$docId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/archive'
    | '/f/$folderId'
    | '/w/$docId'
    | '/api/auth/$'
    | '/api/archive/doc/$docId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/api/archive'
    | '/_app/f/$folderId'
    | '/_app/w/$docId'
    | '/api/auth/$'
    | '/api/archive/doc/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiArchiveRoute: typeof ApiArchiveRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/archive': {
      id: '/api/archive'
      path: '/api/archive'
      fullPath: '/api/archive'
      preLoaderRoute: typeof ApiArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/f/$folderId': {
      id: '/_app/f/$folderId'
      path: '/f/$folderId'
      fullPath: '/f/$folderId'
      preLoaderRoute: typeof AppFFolderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/w/$docId': {
      id: '/_app/w/$docId'
      path: '/w/$docId'
      fullPath: '/w/$docId'
      preLoaderRoute: typeof AppWDocIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/archive/doc/$docId': {
      id: '/api/archive/doc/$docId'
      path: '/doc/$docId'
      fullPath: '/api/archive/doc/$docId'
      preLoaderRoute: typeof ApiArchiveDocDocIdRouteImport
      parentRoute: typeof ApiArchiveRoute
    }
  }
}

interface AppRouteChildren {
  AppFFolderIdRoute: typeof AppFFolderIdRoute
  AppWDocIdRoute: typeof AppWDocIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFFolderIdRoute: AppFFolderIdRoute,
  AppWDocIdRoute: AppWDocIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiArchiveRouteChildren {
  ApiArchiveDocDocIdRoute: typeof ApiArchiveDocDocIdRoute
}

const ApiArchiveRouteChildren: ApiArchiveRouteChildren = {
  ApiArchiveDocDocIdRoute: ApiArchiveDocDocIdRoute,
}

const ApiArchiveRouteWithChildren = ApiArchiveRoute._addFileChildren(
  ApiArchiveRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiArchiveRoute: ApiArchiveRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
