/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppFFolderIdRouteImport } from './routes/_app.f.$folderId'
import { Route as AppWDocIdRouteImport } from './routes/_app.w.$docId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFFolderIdRoute = AppFFolderIdRouteImport.update({
  id: '/f/$folderId',
  path: '/f/$folderId',
  getParentRoute: () => AppRoute,
} as any)
const AppWDocIdRoute = AppWDocIdRouteImport.update({
  id: '/w/$docId',
  path: '/w/$docId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/f/$folderId': typeof AppFFolderIdRoute
  '/w/$docId': typeof AppWDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/f/$folderId': typeof AppFFolderIdRoute
  '/w/$docId': typeof AppWDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/f/$folderId': typeof AppFFolderIdRoute
  '/_app/w/$docId': typeof AppWDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/f/$folderId' | '/w/$docId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/f/$folderId' | '/w/$docId'
  id: '__root__' | '/' | '/_app' | '/_app/f/$folderId' | '/_app/w/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/f/$folderId': {
      id: '/_app/f/$folderId'
      path: '/f/$folderId'
      fullPath: '/f/$folderId'
      preLoaderRoute: typeof AppFFolderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/w/$docId': {
      id: '/_app/w/$docId'
      path: '/w/$docId'
      fullPath: '/w/$docId'
      preLoaderRoute: typeof AppWDocIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFFolderIdRoute: typeof AppFFolderIdRoute
  AppWDocIdRoute: typeof AppWDocIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFFolderIdRoute: AppFFolderIdRoute,
  AppWDocIdRoute: AppWDocIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
